routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['middleware' => 'localization', 'prefix' => Session::get('app.locale')], function() {

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'qlch',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/', 'HomeController@index')->name('index');

    Route::get('/forgot-password', function () {
        return view('admin.forms.forgot_password');
    })->name('forgot-password');

    Route::get('/user/index','UserController@index')->name('user.index');
    Route::get('/user/create','UserController@create')->name('user.create');
    Route::get('/user/change-password','UserController@changePassWord')->name('user.change_password');
    Route::post('/user/save-change-password','UserController@saveChangePassWord')->name('user.save_change_pass');
    Route::post('/user/register','RegisterController@register')->name('user.register');
    Route::get('/user/edit/{id}','UserController@edit')->name('user.edit');
    Route::post('/user/update/{id}','UserController@update')->name('user.update');
    Route::delete('/user/delete/{id}','UserController@delete')->name('user.delete');

    Route::get('/permission','PermissionController@index')->name('permission.index');
    Route::post('/permission/update','PermissionController@update')->name('permission.update');

    Route::get('/roles','RoleController@index')->name('role.index');
    Route::get('/roles/create','RoleController@create')->name('role.create');
    Route::get('/roles/create/user','RoleController@createUser')->name('role.create_user');
    Route::post('/roles/store/user','RoleController@storeUser')->name('role.store.user');
    Route::post('/roles/save','RoleController@save')->name('role.save');
    Route::post('/roles/update','RoleController@update')->name('role.update');
    Route::delete('/roles/delete/{id}','RoleController@delete')->name('role.delete');

    Route::get('/invoice/index','InvoiceController@index')->name('invoice.index');
    Route::get('/invoice/list','InvoiceController@list')->name('invoice.list');
    Route::get('/invoice/customer-pay','InvoiceController@customerPay')->name('invoice.customer_pay');
    Route::post('/invoice/customer-pay-post','InvoiceController@customerPayPost')->name('invoice.customer_pay_post');
    Route::post('/invoice/change-status','InvoiceController@chaneStatusInvoice')->name('invoice.status');
    Route::get('/invoice/censorship','InvoiceController@getInvoiceCensorship')->name('invoice.censorship');
    Route::post('/invoice/is-censorship','InvoiceController@isCensorship')->name('invoice.is-censorship');
    Route::delete('/invoice/delete/{id}','InvoiceController@delete')->name('invoice.delete');
    Route::get('/invoice/report','InvoiceController@reportInvoice')->name('invoice.report');
    Route::get('/invoice/report/debt','InvoiceController@reportInvoiceDebt')->name('invoice.report.debt');
    Route::get('/invoice/search/name-production','InvoiceController@searchNameProduction')->name('invoice.search.name_production');

    Route::get('/customers','CustomerController@index')->name('customer.index');
    Route::get('/customers/create','CustomerController@create')->name('customer.create');
    Route::get('/customer-edit/{id}','CustomerController@edit')->name('customer.edit');
    Route::get('/customer-debt','CustomerController@getCustomerDebt')->name('customer.debt');
    Route::get('/customer/search/customer-invoice','CustomerController@getCustomerInvoice')->name('search.customer_invoice');
    Route::get('/customer/report/retail','CustomerController@reportRetail')->name('customer.report.retail');
    Route::get('/customer/report/wholesale','CustomerController@reportWholesale')->name('customer.report.wholesale');
    Route::get('/customer/{id}/list-invoice','CustomerController@getlistInvoice')->name('custome_list_invoice');
    Route::post('/customer/invoice-infor','CustomerController@getCustomerInvoiceInfor')->name('custome_invoice_infor');
    Route::post('/customer/store','CustomerController@store')->name('customer.store');
    Route::post('/customer/update/{id}','CustomerController@update')->name('customer.update');
    Route::delete('/customer/delete/{id}','CustomerController@delete')->name('customer.delete');
    Route::get('/customer/history-pays/{id}','CustomerController@historyPays')->name('customer.history_pays');
});

// ==== inoice ====
Route::group([
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/create-order','InvoiceController@create')->name('create-order');
    Route::post('/invoice/save','InvoiceController@save')->name('invoice/save');
    Route::get('/invoice/print/{id}','InvoiceController@printInvoice')->name('invoice/print');
    Route::get('/invoice/print_back/{id}','InvoiceController@printInvoiceBack')->name('invoice/printBack');
    Route::get('/invoice/printA4/{id}','InvoiceController@printInvoiceA4')->name('invoice/printA4');
});

app/Http/Controllers/Admin/InvoiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Customer;
use App\CustomerInvoicePay;
use App\Http\Controllers\Controller;
use App\Invoice;
use App\InvoiceDetail;
use App\InvoicePay;
use App\ProductName;
use App\User;
use Carbon\Carbon;
use DB;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Log;

class InvoiceController extends Controller
{
    const LIMIT = 50;
    const MONEY_PENCE = 500;

    public function create()
    {
        if(!Auth::user()->hasPermissionTo('create invoice')) {
            return view('admin.error_permission');
        }
        $invoiceDetail = new InvoiceDetail;
        return view('admin.invoice.create_order', [
            'arrUnit' => $invoiceDetail->nameUnit(),
        ]);
    }

    /**
     * save invoice
     * @param  Request $request
     * @return [type]           [description]
     */
    public function save(Request $request)
    {
        if(!Auth::user()->hasPermissionTo('create invoice')) {
            return view('admin.error_permission');
        }
        $arrData = $this->getValueSerialize($request->data);
        $validator = Validator::make($arrData, [
            'customer_name' => ['required', 'max:255'],
            'name[]' => ['required'],
        ], [
            'customer_name.required' => 'Tên khách hàng không để trống',
            'customer_name.max' => 'Tên khách hàng lớn hơn 255 ký tự',
            'name[].required' => 'Đơn hàng không có sản phẩm',
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()->all()]);
        }

        if ($arrData['type'] == Customer::WHOLESALE) {
            $customer = Customer::where('name', $arrData['customer_name'])->where('type', Customer::WHOLESALE)->first();
        } elseif (!empty($arrData['customer_phone'])) {
            $customer = Customer::where('name', $arrData['customer_name'])->where('type', Customer::WHOLESALE)->first();
        } else {
            $customer = false;
        }

        DB::beginTransaction();
        try {
            $dataDetail = $this->processingInvoiceDetail($arrData);
            $arrData['guests_pay'] = (int) str_replace('.', '', $arrData['guests_pay']);
            if (($dataDetail['total'] / self::MONEY_PENCE) > ($arrData['guests_pay'] / self::MONEY_PENCE)
                && ($dataDetail['total'] - $arrData['guests_pay']) < 999) {
                return response()->json(['error' => ['Làm tròn số tiền hóa đơn lên hoặc tiền nợ lớn hơn 1.000 đ']]);
            }
            if (($dataDetail['total'] / self::MONEY_PENCE) > ($arrData['guests_pay'] / self::MONEY_PENCE) &&
                empty($arrData['customer_phone'])) {
                return response()->json(['error' => ['Hóa đơn bán thiếu cần điền số điện thoại']]);
            }
            if (!$customer) {
                $customer_id = $this->processingCustemer($arrData, $customer);
            } else {
                $customer_id = $customer->id;
            }

            $dataInvoice = [
                'user_id' => Auth::id(),
                'customer_id' => $customer_id,
                'total_money' => $dataDetail['total'],
                'type' => $arrData['type'],
                'guest_pay' => $arrData['guests_pay'],
            ];

            $idInvoice = Invoice::create($dataInvoice)->id;

            //== get ids production ====
            $arrIdProd = [];
            foreach ($dataDetail['dataDetail'] as $key => $item) {
                $dataDetail['dataDetail'][$key]['invoice_id'] = $idInvoice;
                if (!is_numeric($dataDetail['dataDetail'][$key]['product_name_id'])) {
                    $idProd = ProductName::create(['name' => $dataDetail['dataDetail'][$key]['product_name_id']])->id;
                    $dataDetail['dataDetail'][$key]['product_name_id'] = $idProd;
                }
                InvoiceDetail::create($dataDetail['dataDetail'][$key]);
            }
            //== lay thong tin no cua user
            $customerPay = CustomerInvoicePay::where('customer_id', $customer_id)->first();
            if ($customerPay) {
                $customerPay->total_money_invoice += $dataInvoice['total_money'];
                $customerPay->total_guest_pay += $dataInvoice['guest_pay'];
                $customerPay->debt = $customerPay->total_guest_pay - $customerPay->total_money_invoice;
                if ($customerPay->debt < self::MONEY_PENCE) {
                    $customerPay->debt = 0;
                }
                $customerPay->update();
            } else {
                $data = [
                    'customer_id' => $customer_id,
                    'total_money_invoice' => $dataInvoice['total_money'],
                    'total_guest_pay' => $dataInvoice['guest_pay'],
                    'debt' => $dataInvoice['guest_pay'] - $dataInvoice['total_money'],
                ];

                if ($data['debt'] > 0 && $data['debt'] < self::MONEY_PENCE) {
                    $data['debt'] = 0;
                }

                CustomerInvoicePay::create($data);
            }

            $result = [
                'succes' => 1,
                'data' => $idInvoice,
            ];
            DB::commit();
            return response($result);
        } catch (Exception $ex) {
            DB::rollback();
            Log::info($ex);
            report($ex);
        }
    }

    /**
     * su ly du lieu post ajax serializeArray
     * @param  [array] $data
     * @return [type]
     */
    public function getValueSerialize($data)
    {
        $arrData = [];
        if (count($data)) {
            foreach ($data as $item) {
                if (strpos($item['name'], '[]') !== false) {
                    $arrData[$item['name']][] = $item['value'];
                } else {
                    $arrData[$item['name']] = $item['value'];
                }
            }
        }
        if (isset($arrData['type']) && $arrData['type'] == 'on') {
            $arrData['type'] = Customer::WHOLESALE;
        } else {
            $arrData['type'] = Customer::RETAIL;
        }
        if (isset($arrData['customer_name']) && is_numeric($arrData['customer_name'])) {
            $item = Customer::find($arrData['customer_name']);
            $arrData['customer_name'] = $item->name;
        }
        return $arrData;
    }

    /**
     * Lưu hóa đơn sử lý lưu thông tin khách hàng
     * @param  [array] $arrData
     * @return [int]
     */
    public function processingCustemer($arrData, $customer)
    {
        if ($customer) {
            return $customer_id = $customer->id;
        }

        $cus = new Customer;
        $customer = $cus->findCus($arrData['customer_name'], $arrData['customer_phone']);
            if ($customer) {
            $customer_id = $customer->id;
        } else {
            $data = [
                'name' => $arrData['customer_name'],
                'phone' => $arrData['customer_phone'],
                'type' => $arrData['type'],
                'address' => $arrData['customer_address'],
            ];
            $customer_id = Customer::create($data)->id;
        }
        return $customer_id;
    }

    /**
     * xử lý dữ liệu chi tiết hóa đơn
     * @param  [array] $arrData
     * @return [int]
     */
    public function processingInvoiceDetail($arrData)
    {
        $total = 0;
        $error = [];
        foreach ($arrData['name[]'] as $key => $value) {
            if (empty($value)) {
                continue;
            }
            if (empty($arrData['price[]'][$key]) || empty($arrData['quantity[]'][$key])) {
                $error = ['Đơn hàng không có số lượng hoặc đơn giá.'];
                break;
            }
            $dataDetail[$key] = [
                'unit_id' => $arrData['unit[]'][$key],
                'product_name_id' => $value,
                'price' => (int) str_replace('.', '', $arrData['price[]'][$key]),
                'quantity' => (int) $arrData['quantity[]'][$key],
                'discount' => empty($arrData['discount[]'][$key]) ? 0 : $arrData['discount[]'][$key],
            ];
            $totalTemp = Invoice::calculationDiscountInvoice($dataDetail[$key]['price'], $dataDetail[$key]['quantity'], $dataDetail[$key]['discount']);
            $total += $totalTemp;
        }
        return [
            'error' => $error,
            'dataDetail' => $dataDetail,
            'total' => (int) $total,
        ];
    }

    /**
     * in hoa don
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function printInvoice($id)
    {
        if(!Auth::user()->hasPermissionTo('create invoice')) {
            return view('admin.invoice.print_order', [
                'invoices' => [],
                'arrUnit' => [],
            ]);
        }
        $invoice = new Invoice;
        $invoiceDetail = new InvoiceDetail;
        return view('admin.invoice.print_order', [
            'invoices' => $invoice->getAll($id),
            'arrUnit' => $invoiceDetail->nameUnit(),
        ]);
    }

    /**
     * in hoa don
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function printInvoiceA4($id)
    {
        if(!Auth::user()->hasPermissionTo('create invoice')) {
            return view('admin.invoice.print_order', [
                'invoices' => [],
                'arrUnit' => [],
            ]);
        }
        $invoice = new Invoice;
        $invoiceDetail = new InvoiceDetail;
        return view('admin.invoice.print_orderA4', [
            'invoices' => $invoice->getAll($id),
            'arrUnit' => $invoiceDetail->nameUnit(),
        ]);
    }

    /**
     * in hoa don
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function printInvoiceBack($id)
    {
        if(!Auth::user()->hasPermissionTo('create invoice')) {

resources/views/admin/invoice/create_order.blade.php
@extends('admin.layouts.default')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/invoice/invoice.css') }}">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
@endsection

@section('content')
<div class="alert alert-danger print-error-msg" style="display:none">
    <ul style="margin: 0px"></ul>
</div>
<div id="invoice" class="create_invoice">
    <div class="invo-header text-center">
        {{-- <h3>Tạo hóa đơn bán hàng</h3> --}}
    </div>
    <form action="" method="get"  id="form-create-order">
        @csrf
        <div class="invo-header-cus">
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label text-right-sm">Họ và tên:<sup class="red">*</sup></label>
                <div class="col-sm-5">
                    {{-- <input type="name" name="customer_name" class="form-control" placeholder="Nhập tên khách hàng" required> --}}
                    <select  id="customerName" name="customer_name" class="form-control" placeholder="Nhập tên khách hàng"></select>
                </div>
                <div class="col-sm-2">
                    <input type="checkbox" id="toggle-two" name="type" data-offstyle="success">
                    <script>
                      $(function() {
                        $('#toggle-two').bootstrapToggle({
                          on: 'Bán sỉ',
                          off: 'Bán lẻ'
                        });
                      })
                    </script>
                </div>
                <div class="col-sm-3 text-right-sm">
                    <button type="reset" class="btn btn-success reset-table-order">Refresh hóa đơn</button>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label text-right-sm">Số điện thoại:</label>
                <div class="col-sm-5">
                    <input type="number" name="customer_phone" class="form-control" placeholder="Nhập số điện thoại" id="cus_phone">
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label text-right-sm">Địa chỉ:</label>
                <div class="col-sm-5">
                    <input type="address" name="customer_address" class="form-control" placeholder="Nhập địa chỉ" id="cus_address">
                </div>
                {{-- <div class="col-sm-5 text-right-sm">
                    <button type="submit" class="btn btn-primary btnprn" id="save-order">Lưu hóa đơn</button>
                </div> --}}
            </div>
            
        </div>
        <table class="table table-bordered table-hover table-order-create">
            <thead>
                <tr class="text-center bg-color-blue">
                    <th scope="col" class="with-10">#</th>
                    <th scope="col" class="width-min-250">Tên hàng</th>
                    <th scope="col" class="width-c_order-100">Đơn vị</th>
                    <th scope="col" class="width-c_order-150">Số lượng</th>
                    <th scope="col" class="width-c_order-200">Đơn giá</th>
                    <th scope="col" class="width-c_order-200">CK (%)</th>
                    <th scope="col" class="width-c_order-200">Thành tiền</th>
                </tr>
            </thead>
            <tbody>
                <?php $hidden = '' ?>
                @for ($i = 0; $i < 20; $i++)
                {{-- <td><input type="text" name='name[]' class="text-left"></td> --}}
                <?php if($hidden == '' && $i > 4) {
                        $hidden = 'd-none';
                    }
                ?>
                <tr class="{{ $hidden }} row-{{ $i }}">
                    <th scope="row">{{ ($i + 1 )}}</th>
                    <td>
                        <select name="name[]" class="form-control search-name-production-invoice"></select>
                    </td>
                    <td>
                        <select class="form-control form-control-sm" name='unit[]'>
                            @foreach($arrUnit as $key => $unit)
                                <option value="{{ $key }}">{{ $unit }}</option>
                            @endforeach
                        </select>
                    </td>
                    <td><input type="number" name='quantity[]' class="type-quantity input-quantity" min="0"></td>
                    <td><input type="text" name='price[]' data-type="currency" class="type-quantity input-price" min="0"></td>
                    <td><input type="text" name="discount[]" class='allownumericwithdecimal type-quantity input-discount'></td>
                    <td class="into-money"></td>
                </tr>
                @endfor
            </tbody>
        </table>
        <div class="row">
            <div class="col-md-6">
                <button type="button" class="btn btn-info text-left" id="add-new-order" data-row="5">Thêm 5 dòng</button>
                <button type="button" class="btn btn-primary btnprn" style="margin-left: 40px" id="save-order">Lưu và in hóa đơn</button>
            </div>
            <div class="col-md-6 box-money">
                <table>
                    <tbody>
                        <tr>
                            <td>Tổng tiền hóa đơn: </td>
                            <td class="total-money text-right"><span>0 &#8363;</span></td>
                        </tr>
                        <tr>
                            <td class="invoice-debt">Hóa đơn nợ: </td>
                            <td class="text-right money_debt"><span>0</span> đ</td>
                        </tr>
                        <tr>
                            <td>Thanh toán: </td>
                            <td class="text-right"><input type="text" name="guests_pay" id="currency-field" value="0" data-type="currency" > ₫</div></td>
                        </tr>
                        <tr>
                            <td class="text-debt">Còn nợ</td>
                            <td class="text-right money_total_debt"><span>0 đ</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>
@endsection

@section('script')
    <script>
        var  urlPrint = "{{ route('invoice/print', ['id' => 'tamp']) }}";
        var  urlInvoiceSave = "{{ route('invoice/save') }}";
        var urlSerachCustomer = "{{ route("admin.search.customer_invoice") }}";
        var urlCustomerInfor = "{{ route('admin.custome_invoice_infor')}}";
        var urlSearchNameProInvoice = "{{ route('admin.invoice.search.name_production')}}";
    </script>

    <script src="{{ asset('js/invoice/create.js')}}"></script>
    <script src="{{ asset('js/print/print_order.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    <script type="text/javascript">
     
    </script>
@endsection

resources/views/admin/invoice/list.blade.php
@extends('admin.layouts.default')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/invoice/invoice.css') }}">
    <style>
        .badge {
            padding: 5px .6em;
        }
    </style>
@endsection

<?php
    use Carbon\Carbon;
    use App\Core;
    use App\Invoice;
    
    $objInvoice = new Invoice();
?>

@section('content')
<div id="list_invoice">
    <form action="{{route('admin.invoice.list')}}" method="get" class="form-inline" >
        <div class="text-right" style="width: 100%; margin-bottom: 10px">
            <a href="{{route('admin.invoice.list')}}" class="btn btn-info" role="button">Refresh tìm kiếm</a>
            <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i> tìm kiếm</button>
        </div>
        <table class="table table-bordered ">
            <thead>
                <tr class="text-center bg-info">
                    <th scope="col" class="with-10">#</th>
                    <th scope="col" class="width-150">Mã HD</th>
                    <th scope="col">Tên khách hàng</th>
                    {{-- <th scope="col">Tên nhân viên</th> --}}
                    <th scope="col">Ngày bán</th>
                    <th scope="col">Loại HĐ</th>
                    <th scope="col">Ghi chú</th>
                    <th scope="col">Trạng thái</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td>
                        <input type="search" name="invoice_id"  class="form-control" placeholder="search mã hóa đơn" style="width: 100%"
                        value="{{ array_key_exists('invoice_id', $dataSearch) ? $dataSearch['invoice_id'] : ''}}" style="width: 80px;">
                    </td>
                    <td>
                        <input type="search" name="customer_name"  class="form-control with-100_"
                        value="{{ array_key_exists('customer_name', $dataSearch) ? $dataSearch['customer_name'] : ''}}" placeholder="search tên khách hàng">
                    </td>
                    <td>
                        <input type="date" name="customer_date"  class="form-control" style="width: 100%"
                        value="{{ array_key_exists('customer_date', $dataSearch) ? $dataSearch['customer_date'] : ''}}"></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                @if (count($invoices))
                    <?php $i = Core::getSTT($invoices) ?>
                    @foreach($invoices as $invoice)
                        <tr>
                            <th scope="row" class="text-center">{{ ++$i }}</th>
                            <td class="text-center"> {{ $objInvoice->getCodeInvoice($invoice->id) }}</td>
                            <td>{{ $invoice->customer->name }}</td>
                            {{-- <td>{{ $invoice->user->full_name }}</td> --}}
                            <td>{{ Carbon::parse($invoice->created_at)->format("d-m-Y H:i") }}</td>
                            <td class="text-center">
                                @if ($invoice->type == Invoice::WHOLESALE)
                                    <span class="badge badge-pill badge-success">Bán sỉ</span>
                                @else
                                    <span class="badge badge-pill badge-primary">Bán lẻ</span>
                                @endif
                            </td>
                            <td class="max-with-md-300">{{ $invoice->note }}</td>
                            <td class="text-center">
                                <?php $status = $objInvoice->getStatus($invoice); ?>
                                @if ($invoice->status == Invoice::ACTIVE)
                                    <span class="badge badge-success">{{ $status }}</span>
                                @else
                                    <span class="badge badge-danger">{{ $status }}</span>
                                @endif
                            </td>
                            <td class="eye-pen">
                                <button type="button" class="btn btn-info modal-view" title="Xem chi tiết" data-toggle="modal"data-target="#myModal"
                                data-invoice="{{ json_encode([$invoice->total_money,$invoice->guest_pay]) }}"
                                data-detail="{{ $invoice->detail }}"
                                ><i class="fas fa-eye"></i></button>
                                <button type="button" class="btn btn-danger huy-don" title="Hủy hóa đơn" data-toggle="modal" data-target="#myModalDelte" data-id="{{ $invoice->id }}"><i class="fas fa-times" style="padding: 3px 4px"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    </form>
    <div class="text-center">
        {{ $invoices->links() }}
    </div>

    @include('admin.invoice.modals.invoice_detail')
    <!-- The Modal -->
    <div class="modal fade" id="myModalDelte">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                      <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title text-center">Báo hủy hóa đơn</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <form action="{{ route('admin.invoice.status')}}"  method="post">
                        {{ csrf_field() }}
                        <div class="row">
                            <input type="text" name="id" hidden>
                            <div class="form-group" style="width: 100%; padding: 0px 15px">
                              <label for="comment">Nhập lý do hủy đơn:</label>
                              <textarea class="form-control" rows="5" id="comment" name="note" required></textarea>
                            </div>
                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-danger">Gửi</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
    <script>
        $('#list_invoice').on('click', "form .huy-don", function (argument) {
            $("#myModalDelte").find('input[name="id"]').val($(this).attr('data-id'));
        })
    </script>
@endsection