routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['middleware' => 'localization', 'prefix' => Session::get('app.locale')], function() {

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'qlch',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/', 'HomeController@index')->name('index');

    Route::get('/forgot-password', function () {
        return view('admin.forms.forgot_password');
    })->name('forgot-password');

    Route::get('/user/index','UserController@index')->name('user.index');
    Route::get('/user/create','UserController@create')->name('user.create');
    Route::get('/user/change-password','UserController@changePassWord')->name('user.change_password');
    Route::post('/user/save-change-password','UserController@saveChangePassWord')->name('user.save_change_pass');
    Route::post('/user/register','RegisterController@register')->name('user.register');
    Route::get('/user/edit/{id}','UserController@edit')->name('user.edit');
    Route::post('/user/update/{id}','UserController@update')->name('user.update');
    Route::delete('/user/delete/{id}','UserController@delete')->name('user.delete');

    Route::get('/permission','PermissionController@index')->name('permission.index');
    Route::post('/permission/update','PermissionController@update')->name('permission.update');

    Route::get('/roles','RoleController@index')->name('role.index');
    Route::get('/roles/create','RoleController@create')->name('role.create');
    Route::get('/roles/create/user','RoleController@createUser')->name('role.create_user');
    Route::post('/roles/store/user','RoleController@storeUser')->name('role.store.user');
    Route::post('/roles/save','RoleController@save')->name('role.save');
    Route::post('/roles/update','RoleController@update')->name('role.update');
    Route::delete('/roles/delete/{id}','RoleController@delete')->name('role.delete');

    Route::get('/invoice/index','InvoiceController@index')->name('invoice.index');
    Route::get('/invoice/list','InvoiceController@list')->name('invoice.list');
    Route::get('/invoice/customer-pay','InvoiceController@customerPay')->name('invoice.customer_pay');
    Route::post('/invoice/customer-pay-post','InvoiceController@customerPayPost')->name('invoice.customer_pay_post');
    Route::post('/invoice/change-status','InvoiceController@chaneStatusInvoice')->name('invoice.status');
    Route::get('/invoice/censorship','InvoiceController@getInvoiceCensorship')->name('invoice.censorship');
    Route::post('/invoice/is-censorship','InvoiceController@isCensorship')->name('invoice.is-censorship');
    Route::delete('/invoice/delete/{id}','InvoiceController@delete')->name('invoice.delete');
    Route::get('/invoice/report','InvoiceController@reportInvoice')->name('invoice.report');
    Route::get('/invoice/report/debt','InvoiceController@reportInvoiceDebt')->name('invoice.report.debt');
    Route::get('/invoice/search/name-production','InvoiceController@searchNameProduction')->name('invoice.search.name_production');

    Route::get('/customers','CustomerController@index')->name('customer.index');
    Route::get('/customers/create','CustomerController@create')->name('customer.create');
    Route::get('/customer-edit/{id}','CustomerController@edit')->name('customer.edit');
    Route::get('/customer-debt','CustomerController@getCustomerDebt')->name('customer.debt');
    Route::get('/customer/search/customer-invoice','CustomerController@getCustomerInvoice')->name('search.customer_invoice');
    Route::get('/customer/report/retail','CustomerController@reportRetail')->name('customer.report.retail');
    Route::get('/customer/report/wholesale','CustomerController@reportWholesale')->name('customer.report.wholesale');
    Route::get('/customer/{id}/list-invoice','CustomerController@getlistInvoice')->name('custome_list_invoice');
    Route::post('/customer/invoice-infor','CustomerController@getCustomerInvoiceInfor')->name('custome_invoice_infor');
    Route::post('/customer/store','CustomerController@store')->name('customer.store');
    Route::post('/customer/update/{id}','CustomerController@update')->name('customer.update');
    Route::delete('/customer/delete/{id}','CustomerController@delete')->name('customer.delete');
    Route::get('/customer/history-pays/{id}','CustomerController@historyPays')->name('customer.history_pays');
});

// ==== inoice ====
Route::group([
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/create-order','InvoiceController@create')->name('create-order');
    Route::post('/invoice/save','InvoiceController@save')->name('invoice/save');
    Route::get('/invoice/print/{id}','InvoiceController@printInvoice')->name('invoice/print');
    Route::get('/invoice/print_back/{id}','InvoiceController@printInvoiceBack')->name('invoice/printBack');
    Route::get('/invoice/printA4/{id}','InvoiceController@printInvoiceA4')->name('invoice/printA4');
});

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Invoice;
use App\InvoicePay;
use App\Customer;
use App\CustomerInvoicePay;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;

class CustomerController extends Controller
{
    const LIMIT = 50;

    /**
     * [index description]
     * @param  Request  $request
     * @param  Customer $customer
     * @return [type]
     */
    public function index(Request $request, Customer $customer)
    {
        if(!Auth::user()->hasPermissionTo('create customer')) {
            return view('admin.error_permission');
        }

        $dataSearch = [
            'customer_name' => $request->get('customer_name'),
            'customer_phone' => $request->get('customer_phone'),
        ];
        $params = [
            'customers' => $customer->getAll($dataSearch),
            'dataSearch' => $dataSearch,
        ];
        return view('admin.customers.index', $params); 
    }

    /**
     * [create description]
     * @return [type] [description]
     */
    public function create()
    {
        if(!Auth::user()->hasPermissionTo('create customer')) {
            return view('admin.error_permission');
        }
        return view('admin.customers.create'); 
    }

    /**
     * [edit description]
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function edit($id)
    {
        if(!Auth::user()->hasPermissionTo('create customer')) {
            return view('admin.error_permission');
        }
        $customer = Customer::find($id);
        if (!$customer) {
            return redirect()->back()->withErrors('Không tìm khách hàng!');
        }
        $params = [
            'customer' => $customer
        ];
        return view('admin.customers.edit', $params); 
    }

    /**
     * [index description]
     * @param  Request  $request
     * @param  Customer $customer
     * @return [type]
     */
    public function store(Request $request)
    {
        if(!Auth::user()->hasPermissionTo('create customer')) {
            return view('admin.error_permission');
        }
        if ($request->type == Customer::WHOLESALE) {
            $data = [
                'name' => ['required', 'string', 'max:255', 'unique:customers'],
                'phone' => ['required', 'unique:customers'],
            ];
            $message = [
                'name.required' => 'Tên khách hàng không để trống',
                'name.unique' => 'Tên khách hàng bán sỉ đã tồn tại',
                'phone.required' => 'Số điện thoại không để trống',
                'phone.unique' => 'Số điện thoại đã tồn tại'
            ];
        } else {
            $data = [
                'phone' => ['required', 'unique:customers,phone,'],
            ];
            $message = [
                'phone.required' => 'Số điện thoại không để trống',
                'phone.unique' => 'Số điện thoại bán lẻ đã tồn tại'
            ];
        }
        $validator = Validator::make($request->all(), $data, $message);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }
        try {
            Customer::create($request->all());
            return redirect()->back()->with('message', 'Thêm khách hàng thành công!');
        } catch (Exception $ex) {
            Log::info($ex);
            return redirect()->back()->withErrors('Có lỗi sảy ra!');
        }
    }

    /**
     * [index description]
     * @param  Request  $request
     * @param  Customer $customer
     * @return [type]
     */
    public function update($id, Request $request)
    {
        if(!Auth::user()->hasPermissionTo('create customer')) {
            return view('admin.error_permission');
        }
        $customer = Customer::find($id);
        if (!$customer) {
            return redirect()->back()->withErrors('Không tìm khách hàng!');
        }
        if ($customer->type == Customer::WHOLESALE) {
            $data = [
                'name' => ['required', 'string', 'max:255', 'unique:customers,name,' . $id],
                'phone' => ['required', 'unique:customers,phone,' . $id],
            ];
            $message = [
                'name.required' => 'Tên khách hàng không để trống',
                'name.unique' => 'Tên khách hàng bán sỉ đã tồn tại',
                'phone.required' => 'Số điện thoại không để trống',
                'phone.unique' => 'Số điện thoại đã tồn tại'
            ];
        } else {
            $data = [
                'phone' => ['required', 'unique:customers,phone,' . $id],
            ];
            $message = [
                'phone.required' => 'Số điện thoại không để trống',
                'phone.unique' => 'Số điện thoại đã tồn tại'
            ];
        }
        $validator = Validator::make($request->all(), $data, $message);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        try {
            $customer->update($request->all());
            return redirect()->back()->with('message', 'Cập nhật thành công!');
        } catch (Exception $ex) {
            Log::info($ex);
            return redirect()->back()->withErrors('Có lỗi sảy ra!');
        }
    }

    /**
     * [delete description]
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function delete($id)
    {
        if(!Auth::user()->hasPermissionTo('create customer')) {
            return view('admin.error_permission');
        }
        $customer = Customer::find($id);
        if (!$customer) {
            return redirect()->back()->withErrors('Không tìm khách hàng!');
        }
        $invoice = Invoice::where('customer_id', $id)->first();
        if ($invoice) {
            return redirect()->back()->withErrors('Khách hàng có hóa đơn không thể xóa!');
        }
        try {
            Customer::destroy($id);
            return redirect()->back()->with('message', 'Xóa khách hàng thành công!');
        } catch (Exception $ex) {
            Log::info($ex);
            return redirect()->back()->withErrors('Có lỗi sảy ra!');
        }
    }

    /**
     * tìm kiếm khách hàng
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function getCustomerInvoice(Request $request)
    {
        $customer = new Customer;
        if ($request->input('type') != 'false') {
            $customers = $customer->searchCusWholesale($request->input('search', ''));
        } else {
            // $customers = $customer->searchCusRetails($request->input('search', ''), $request->input('phone', ''));
            $customers = [];
        }
        return ['results' => $customers];
    }

    /**
     * get thông tin khách hàng khi tạo hóa đơn
     * @param  Request $request
     * @return [type]
     */
    public function getCustomerInvoiceInfor(Request $request)
    {
        $params = [
            'total_debt' => 0,
            'id' => '',
            'name' => '',
            'phone' => '',
            'address' => '',
        ];
        $id = $request->valueName;
        $type = $request->type != 'false' ? Customer::WHOLESALE : Customer::RETAIL;
        $phone = $request->phone;

        $objCustomer = new Customer;
        if (is_numeric($id)) {
            $customer = $objCustomer->getCusInvoiceById($id);
            if (!$customer) {
                $customer = Customer::find($id);
                $params['phone'] = $customer->phone;
                $params['name'] = $customer->name;
                $params['id'] = $customer->id;
                $params['address'] = $customer->address;
                return $params;
            }
        } elseif (!empty($phone)) {
            $customer = $objCustomer->getCusInvoiceByPhone($type, $phone);
        } else {
            $customer = false;
        }
        if ($customer) {
            $params['total_debt'] += $customer->debt;
            $params['phone'] = $customer->phone;
            $params['name'] = $customer->name;
            $params['id'] = $customer->id;
            $params['address'] = $customer->address;
        }
        return $params;
    }

    /**
     * danh sách hóa đơn viên bán sỉ
     * @return [type] [description]
     */
    public function reportWholesale()
    {
        if(!Auth::user()->hasPermissionTo('report invoice')) {
            return view('admin.error_permission');
        }
        $customer = new Customer();
        $params = [
            'customers' => $customer->getCusInvoiceByType(Customer::WHOLESALE),
            'cateUser' => 'Danh sách khách hàng bán sỉ',
        ];
        return view('admin.customers.report_invoice', $params);
    }

    /**
     * danh sách hóa đơn viên bán lẻ
     * @return [type] [description]
     */
    public function reportRetail()
    {
        if(!Auth::user()->hasPermissionTo('report invoice')) {
            return view('admin.error_permission');
        }
        $customer = new Customer();
        $params = [
            'customers' => $customer->getCusInvoiceByType(Customer::RETAIL),
            'cateUser' => 'Danh sách khách hàng bán lẻ',
        ];
        return view('admin.customers.report_invoice', $params);
    }

    /**
     * get danh sách khách hàng nợ tiền
     * @return [type] [description]
     */
    public function getCustomerDebt()
    {
        $customer = new CustomerInvoicePay();

        $params = [
            'customers' => $customer->getCustomerDebt(),
        ];

        return view('admin.customers.report_customer_debt', $params);
    }

    /**
     * danh sách hóa đơn theo khách hàng
     * @return [type] [description]
     */
    public function getlistInvoice($id)
    {
        if(!Auth::user()->hasPermissionTo('report invoice')) {
            return view('admin.error_permission');

resources/views/admin/customers/create.blade.php
@extends('admin.layouts.default')

@section('css')

@endsection
<?php
    use App\Customer;
?>
@section('content')
<div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Thêm khách hàng mới</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('admin.customer.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Họ và tên:<sup class="red">*</sup> </label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">Số ĐT: <sup class="red">*</sup></label>

                            <div class="col-md-6">
                                <input id="phone" type="number" class="form-control @error('phone') is-invalid @enderror" name="phone" required autocomplete="phone" autofocus>

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">Địa chỉ:</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" autocomplete="address" autofocus>

                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="birthday" class="col-md-4 col-form-label text-md-right">Trạng thái:</label>
                            <div class="col-md-6">
                                <select class="form-control" name="type">
                                    <option value="{{ customer::WHOLESALE}}">Bán sỉ</option>
                                    <option value="{{ customer::RETAIL}}">Bán lẻ</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Tạo khách hàng') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
   <div class="container">
       
   </div>
@endsection

resources/views/admin/customers/edit.blade.php
@extends('admin.layouts.default')

@section('css')

@endsection
<?php
    use App\customer;
?>
@section('content')
<div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Cập nhật thông tin khách hàng</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.customer.update', ['id' => $customer->id]) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Họ và tên:<sup class="red">*</sup> </label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $customer->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">Số ĐT:</label>

                            <div class="col-md-6">
                                <input id="phone" type="number" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ $customer->phone }}" autocomplete="phone" autofocus>

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">Địa chỉ:</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" value="{{ $customer->address }}" autocomplete="address" autofocus>

                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Cập nhật') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
   <div class="container">
       
   </div>
@endsection

resources/views/admin/customers/index.blade.php
@extends('admin.layouts.default')

@section('css')
    <style>
        .badge {
            padding: 5px .6em;
        }
    </style>
@endsection
<?php
    use Carbon\Carbon;
    use App\Core;
    use App\customer;
?>

@section('content')
<div class="">
    <form action="{{ route('admin.customer.index') }}" method="get" class="form-inline" >
        <div class="row" style="width: 100%">
            <div class="col-md-6">
                <a href="{{ route('admin.customer.create') }}" class="btn btn-success mb-4" role="button" target="_bank">
                    <i class="fas fa-plus"></i> Thêm khách hàng mới
                </a>
            </div>
             <div class="col-md-6 text-right">
                <a href="{{route('admin.customer.index')}}" class="btn btn-info" role="button">Refresh tìm kiếm</a>
                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i> tìm kiếm</button>
            </div>
        </div>
        <table class="table table-hover table-striped view-customer">
            <thead class="bg-success">
                <tr class="">
                    <th scope="col">STT</th>
                    <th scope="col">Tên khách hàng</th>
                    <th scope="col">Số điện thoại</th>
                    <th scope="col">Địa chỉ</th>
                    <th scope="col">Khách hàng</th>
                    <th scope="col">Ngày tạo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td>
                        <input type="search" name="customer_name"  class="form-control" style="width: 100%"
                        value="{{ array_key_exists('customer_name', $dataSearch) ? $dataSearch['customer_name'] : ''}}" placeholder="search tên khách hàng">
                    </td>
                    <td>
                        <input type="number" name="customer_phone"  class="form-control" style="width: 100%" placeholder="search số điện thoại" value="{{ array_key_exists('customer_phone', $dataSearch) ? $dataSearch['customer_phone'] : ''}}"></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <?php $i = Core::getSTT($customers) ?>
                @foreach($customers as $key => $customer)
                <tr>
                    <th scope="row">{{ ++$i }}</th>
                    <td>{{ $customer->name }}</td>
                    <td>{{ $customer->phone }}</td>
                    <td>{{ $customer->address }}</td>
                    <td>
                        @if ($customer->type == Customer::WHOLESALE)
                            <span class="badge badge-pill badge-success">Bán sỉ</span>
                        @else
                            <span class="badge badge-pill badge-primary">Bán lẻ</span>
                        @endif
                    </td>
                    <td>{{ Carbon::parse($customer->created_at)->format("d-m-Y") }}</td>
                    <td class="view-pen-trash">
                        <a href="{{ route('admin.customer.edit', ['id' => $customer->id]) }}" class="btn btn-primary"data-toggle="tooltip" title="sửa thông tin" data-placement="left" role="button"><i class="fas fa-pen"></i>
                        </a>
                        @if (!$customer->hasRole('sup admin'))
                        <a class="btn btn-danger delete-message-name" data-toggle="tooltip" title="khách hàng" data-placement="right"
                            data-name="{{ $customer->name }}" style="color: #ffff"
                            data-message="Bạn có muốn xóa khách hàng: "><i class="far fa-trash-alt"></i>
                            <form class="delete" action="{{ route('admin.customer.delete', ['id' => $customer->id]) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                            </form>
                        </a>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </form>
    <div class="text-center">
        {{ $customers->links() }}
    </div>
</div>

@endsection

@section('script')
    <script src="{{ asset('js/user/index.js') }}"></script>
@endsection

resources/views/admin/customers/list_invoice.blade.php
@extends('admin.layouts.default')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/invoice/invoice.css') }}">
    <style>
        .badge {
            padding: 5px .6em;
        }
    </style>
@endsection

<?php
    use Carbon\Carbon;
    use App\Core;
    use App\Invoice;

    $objInvoice = new Invoice();
    $totalMoney = 0;
    $totalGuestPay = 0;
    $invoice = $invoices->first();
?>

@section('content')
<div id="list_invoice">
    <form action="{{route('admin.invoice.list')}}" method="get" class="form-inline" >
        <div class="text-right" style="width: 100%; margin-bottom: 10px">
            <h5 class="text-left">Danh sách hóa đơn KH: {{ $customer->name }}</h5>
            @if ($invoice)
                <a href="{{route('admin.customer.history_pays', ['id' => $invoice->id])}}">Lịch sử thanh toán</a>
            @endif
        </div>
        <table class="table table-bordered ">
            <thead>
                <tr class="text-center bg-info">
                    <th scope="col" class="with-10">#</th>
                    <th scope="col">Mã HD</th>
                    <th scope="col">Tên nhân viên</th>
                    <th scope="col">Ngày bán</th>
                    <th scope="col">Loại HĐ</th>
                    <th scope="col">Tổng hóa đơn</th>
                    <th scope="col">Thanh toán</th>
                    <th scope="col">Ghi chú</th>
                    <th scope="col">Trạng thái</th>
                </tr>
            </thead>
            <tbody>
                @if (count($invoices))
                    <?php $i = Core::getSTT($invoices) ?>
                    @foreach($invoices as $invoice)
                        <tr>
                            <th scope="row" class="text-center">{{ ++$i }}</th>
                            <td class="text-center width-150"> {{ $objInvoice->getCodeInvoice($invoice->id) }}</td>
                            <td>{{ $invoice->user->full_name }}</td>
                            <td class="text-center">{{ Carbon::parse($invoice->created_at)->format("d-m-Y H:i") }}</td>
                            <td class="text-center">
                                @if ($invoice->type == Invoice::WHOLESALE)
                                    <span class="badge badge-pill badge-success">Bán sỉ</span>
                                @else
                                    <span class="badge badge-pill badge-primary">Bán lẻ</span>
                                @endif
                            </td>

                            <td>{{ number_format($invoice->total_money) }}</td>
                            <td>{{ number_format($invoice->guest_pay) }}</td>
                            <td class="max-with-md-300">{{ $invoice->note }}</td>
                            <td class="text-center">
                                <?php $status = $objInvoice->getStatus($invoice); ?>
                                @if ($invoice->status == Invoice::ACTIVE)
                                    <span class="badge badge-success">{{ $status }}</span>
                                @else
                                    <span class="badge badge-danger">{{ $status }}</span>
                                @endif
                            </td>
                            <?php
                                $totalMoney += $invoice->total_money;
                                $totalGuestPay += $invoice->guest_pay;
                            ?>
                        </tr>
                    @endforeach
                        <td>#</td>
                        <td colspan="4">Tổng tiền: </td>
                        <td>{{ number_format($totalMoney) }}</td>
                        <td>{{ number_format($totalGuestPay) }}</td>
                        <td colspan="2"></td>
                @endif
            </tbody>
        </table>
    </form>
    <div class="text-center">
        {{ $invoices->links() }}
    </div>
</div>
@endsection

@section('script')
@endsection