routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['middleware' => 'localization', 'prefix' => Session::get('app.locale')], function() {

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'qlch',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/', 'HomeController@index')->name('index');

    Route::get('/forgot-password', function () {
        return view('admin.forms.forgot_password');
    })->name('forgot-password');

    Route::get('/user/index','UserController@index')->name('user.index');
    Route::get('/user/create','UserController@create')->name('user.create');
    Route::get('/user/change-password','UserController@changePassWord')->name('user.change_password');
    Route::post('/user/save-change-password','UserController@saveChangePassWord')->name('user.save_change_pass');
    Route::post('/user/register','RegisterController@register')->name('user.register');
    Route::get('/user/edit/{id}','UserController@edit')->name('user.edit');
    Route::post('/user/update/{id}','UserController@update')->name('user.update');
    Route::delete('/user/delete/{id}','UserController@delete')->name('user.delete');

    Route::get('/permission','PermissionController@index')->name('permission.index');
    Route::post('/permission/update','PermissionController@update')->name('permission.update');

    Route::get('/roles','RoleController@index')->name('role.index');
    Route::get('/roles/create','RoleController@create')->name('role.create');
    Route::get('/roles/create/user','RoleController@createUser')->name('role.create_user');
    Route::post('/roles/store/user','RoleController@storeUser')->name('role.store.user');
    Route::post('/roles/save','RoleController@save')->name('role.save');
    Route::post('/roles/update','RoleController@update')->name('role.update');
    Route::delete('/roles/delete/{id}','RoleController@delete')->name('role.delete');

    Route::get('/invoice/index','InvoiceController@index')->name('invoice.index');
    Route::get('/invoice/list','InvoiceController@list')->name('invoice.list');
    Route::get('/invoice/customer-pay','InvoiceController@customerPay')->name('invoice.customer_pay');
    Route::post('/invoice/customer-pay-post','InvoiceController@customerPayPost')->name('invoice.customer_pay_post');
    Route::post('/invoice/change-status','InvoiceController@chaneStatusInvoice')->name('invoice.status');
    Route::get('/invoice/censorship','InvoiceController@getInvoiceCensorship')->name('invoice.censorship');
    Route::post('/invoice/is-censorship','InvoiceController@isCensorship')->name('invoice.is-censorship');
    Route::delete('/invoice/delete/{id}','InvoiceController@delete')->name('invoice.delete');
    Route::get('/invoice/report','InvoiceController@reportInvoice')->name('invoice.report');
    Route::get('/invoice/report/debt','InvoiceController@reportInvoiceDebt')->name('invoice.report.debt');
    Route::get('/invoice/search/name-production','InvoiceController@searchNameProduction')->name('invoice.search.name_production');

    Route::get('/customers','CustomerController@index')->name('customer.index');
    Route::get('/customers/create','CustomerController@create')->name('customer.create');
    Route::get('/customer-edit/{id}','CustomerController@edit')->name('customer.edit');
    Route::get('/customer-debt','CustomerController@getCustomerDebt')->name('customer.debt');
    Route::get('/customer/search/customer-invoice','CustomerController@getCustomerInvoice')->name('search.customer_invoice');
    Route::get('/customer/report/retail','CustomerController@reportRetail')->name('customer.report.retail');
    Route::get('/customer/report/wholesale','CustomerController@reportWholesale')->name('customer.report.wholesale');
    Route::get('/customer/{id}/list-invoice','CustomerController@getlistInvoice')->name('custome_list_invoice');
    Route::post('/customer/invoice-infor','CustomerController@getCustomerInvoiceInfor')->name('custome_invoice_infor');
    Route::post('/customer/store','CustomerController@store')->name('customer.store');
    Route::post('/customer/update/{id}','CustomerController@update')->name('customer.update');
    Route::delete('/customer/delete/{id}','CustomerController@delete')->name('customer.delete');
    Route::get('/customer/history-pays/{id}','CustomerController@historyPays')->name('customer.history_pays');
});

// ==== inoice ====
Route::group([
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/create-order','InvoiceController@create')->name('create-order');
    Route::post('/invoice/save','InvoiceController@save')->name('invoice/save');
    Route::get('/invoice/print/{id}','InvoiceController@printInvoice')->name('invoice/print');
    Route::get('/invoice/print_back/{id}','InvoiceController@printInvoiceBack')->name('invoice/printBack');
    Route::get('/invoice/printA4/{id}','InvoiceController@printInvoiceA4')->name('invoice/printA4');
});

resources/views/admin/layouts/default.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Hoàng Ánh</title>
    <!-- Custom fonts for this template-->
    <link type="text/css" href="{{ asset('admin/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet">
    
    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('admin/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('admin/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Custom styles for this template-->
    <link href="{{ asset('admin/css/sb-admin-2.min.css') }}" rel="stylesheet">
    <link href='{{ asset('admin/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}' rel='stylesheet' type='text/css'>
    <script src='{{ asset('admin/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}' type='text/javascript'></script>

    <link rel="stylesheet" href="{{ asset('admin/style.css') }}">
    @yield('css')
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
            <!-- Sidebar -->
            @include('admin.layouts.nav')
            <!-- End of Sidebar -->
             
            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">            
                <!-- Main Content -->
                <div id="content">

                    @include('admin.layouts.top_body')
                
                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        {{-- ====== message ======== --}}
                        @if(session()->has('message'))
                            <div class="alert alert-success">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                {{ session()->get('message') }}
                            </div>
                        @endif
                        @if($errors->any())
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    {{ $error}}
                                </div>
                            @endforeach
                        @endif
                        {{-- ======================= --}}
                        @yield('content')
                    </div>
                </div>

                <!-- Footer -->
                @include('admin.layouts.footer')
                <!-- End of Footer -->    
            </div>
            <!-- End of Content Wrapper -->
    </div>

        <!-- End of Content Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('admin/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('admin/js/sb-admin-2.min.js') }}"></script>

    <script src="{{ asset('js/style.js') }}"></script>
    @yield('script')
</body>

</html>

resources/views/admin/layouts/footer.blade.php
<footer class="sticky-footer bg-white">
	<hr>
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
        </div>
    </div>
</footer>

resources/views/admin/layouts/nav.blade.php
<?php
    $userAuth = auth()->user();

    $hoaDon = request()->is('create-order') ||
        request()->is('qlch/invoice/list') ||
        request()->is('qlch/invoice/customer-pay');

    $QLHoaDon = request()->is('qlch/invoice/censorship') ||
        request()->is('qlch/invoice/index');

    $report = request()->is('qlch/invoice/report') ||
        request()->is('qlch/customer-debt') ||
        request()->is('qlch/customer/report/retail') ||
        request()->is('qlch/customer/*/list-invoice') ||
        request()->is('qlch/customer/history-pays/*') ||
        request()->is('qlch/customer/report/wholesale');

    $customer = request()->is('qlch/customers') ||
        request()->is('qlch/customers/create') ||
        request()->is('qlch/customer-edit/*');

    $user = request()->is('qlch/user/index') ||
        request()->is('qlch/user/create');

    $permission = request()->is('qlch/roles/create/user') ||
        request()->is('qlch/roles') ||
        request()->is('qlch/permission');
?>
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('admin.index') }}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Hoàng Ánh</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider">
    
    @if($userAuth->can('create invoice') ||
        $userAuth->can('manager invoice') ||
        $userAuth->can('report invoice'))
    <li class="nav-item">
        <a class="nav-link {{ $hoaDon ? '' : 'collapsed' }}" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-file-invoice"></i>
            <span>Hóa đơn</span>
        </a>
        <div id="collapseTwo" class="collapse {{ $hoaDon ? 'show' : '' }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('create-order') }}">Tạo hóa đơn</a>
                <a class="collapse-item" href="{{ route('admin.invoice.list') }}">Danh sách hóa đơn</a>
                <a class="collapse-item" href="{{ route('admin.invoice.customer_pay') }}">Khách hàng thanh toán</a>
            </div>
        </div>
    </li>
    @endif

    @if($userAuth->can('manager invoice'))
        <li class="nav-item">
            <a class="nav-link {{ $QLHoaDon ? '' : 'collapsed' }}" href="#" data-toggle="collapse" data-target="#managerInvoice" aria-expanded="true" aria-controls="managerInvoice">
                <i class="fas fa-tasks"></i>
                <span>Quản lý hóa đơn</span>
            </a>
            <div id="managerInvoice" class="collapse {{ $QLHoaDon ? 'show' : '' }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{{ route('admin.invoice.censorship') }}">Hóa đơn cần duyệt</a>
                    <a class="collapse-item" href="{{ route('admin.invoice.index') }}">Danh sách hóa đơn</a>
                </div>
            </div>
        </li>
    @endif
    
    @if($userAuth->can('create customer'))
        <li class="nav-item">
            <a class="nav-link {{ $customer ? '' : 'collapsed' }}" href="#" data-toggle="collapse" data-target="#manageCustomer" aria-expanded="true" aria-controls="manageCustomer">
                <i class="fas fa-users"></i>
                <span>Quản lý khách hàng</span>
            </a>
            <div id="manageCustomer" class="collapse {{ $customer ? 'show' : '' }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{{ route('admin.customer.index') }}">Danh sách khách hàng</a>
                    <a class="collapse-item" href="{{ route('admin.customer.create') }}">Thêm khách hàng</a>
                </div>
            </div>
        </li>
    @endif

    @if($userAuth->can('report invoice'))
        <li class="nav-item">
            <a class="nav-link {{ $report ? '' : 'collapsed' }}" href="#" data-toggle="collapse" data-target="#report" aria-expanded="true" aria-controls="report">
                <i class="fas fa-chart-bar"></i>
                <span>Thống kê - báo cáo</span>
            </a>
            <div id="report" class="collapse {{ $report ? 'show' : '' }}" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{{ route('admin.invoice.report') }}">Báo cáo hóa đơn</a>
                    {{-- <a class="collapse-item" href="{{ route('admin.invoice.report.debt') }}">Hóa đơn còn nợ</a> --}}
                    <a class="collapse-item" href="{{ route('admin.customer.debt') }}">Khách hàng còn nợ</a>
                    <a class="collapse-item" href="{{ route('admin.customer.report.wholesale') }}">Khách hàng bán sỉ</a>
                    <a class="collapse-item" href="{{ route('admin.customer.report.retail') }}">Khách hàng bán lẻ</a>
                </div>
            </div>
        </li>
    @endif

    @if($userAuth->can('create user'))
    <li class="nav-item">
        <a class="nav-link {{ $user ? '' : 'collapsed' }}" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
           <i class="fas fa-users-cog"></i>
            <span>Quản lý nhân viên</span>
        </a>
        <div id="collapseUtilities" class="collapse {{ $user ? 'show' : '' }}" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{ route('admin.user.index')}}">Danh sách nhân viên</a>
                <a class="collapse-item" href="{{ route('admin.user.create')}}">Thêm nhân viên</a>
            </div>
        </div>
    </li>
    @endif

    @if($userAuth->can('create roles') ||
        $userAuth->can('create role user') ||
        $userAuth->can('create permission role'))
    <li class="nav-item">
        <a class="nav-link {{ $permission ? '' : 'collapsed' }}" href="#" data-toggle="collapse" data-target="#permission" aria-expanded="true" aria-controls="permission">
            <i class="fas fa-user-cog"></i>
            <span>Phân quyền</span>
        </a>
        <div id="permission" class="collapse {{ $permission ? 'show' : '' }}" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                @can('create role user')
                    <a class="collapse-item" href="{{ route('admin.role.create_user')}}">Cấp chức vụ nhân viên</a>
                @endcan
                @can('create roles')
                    <a class="collapse-item" href="{{ route('admin.role.index')}}">Chức vụ hệ thống</a>
                @endcan
                @can('create permission role')
                    <a class="collapse-item" href="{{ route('admin.permission.index')}}">Phân quyền</a>
                @endcan
            </div>
        </div>
    </li>
    @endif

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

resources/views/admin/layouts/top_body.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"  style="height: 50px">
        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
    
            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                    <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>
    
            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <!-- Counter - Alerts -->
                    <span class="badge badge-danger badge-counter">3+</span>
                </a>
                <!-- Dropdown - Alerts -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                    <h6 class="dropdown-header">
                        Alerts Center
                    </h6>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="mr-3">
                            <div class="icon-circle bg-primary">
                                <i class="fas fa-file-alt text-white"></i>
                            </div>
                        </div>
                        <div>
                            <div class="small text-gray-500">December 12, 2019</div>
                            <span class="font-weight-bold">A new monthly report is ready to download!</span>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="mr-3">
                            <div class="icon-circle bg-success">
                                <i class="fas fa-donate text-white"></i>
                            </div>
                        </div>
                        <div>
                            <div class="small text-gray-500">December 7, 2019</div>
                            $290.29 has been deposited into your account!
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="mr-3">
                            <div class="icon-circle bg-warning">
                                <i class="fas fa-exclamation-triangle text-white"></i>
                            </div>
                        </div>
                        <div>
                            <div class="small text-gray-500">December 2, 2019</div>
                            Spending Alert: We've noticed unusually high spending for your account.
                        </div>
                    </a>
                    <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                </div>
            </li>
    
            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <!-- Counter - Messages -->
                    <span class="badge badge-danger badge-counter">7</span>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                    <h6 class="dropdown-header">
                        Message Center
                    </h6>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                            <div class="status-indicator bg-success"></div>
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                            <div class="small text-gray-500">Emily Fowler · 58m</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                            <div class="status-indicator"></div>
                        </div>
                        <div>
                            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                            <div class="small text-gray-500">Jae Chun · 1d</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                            <div class="status-indicator bg-warning"></div>
                        </div>
                        <div>
                            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                            <div class="status-indicator bg-success"></div>
                        </div>
                        <div>
                            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                            <div class="small text-gray-500">Chicken the Dog · 2w</div>
                        </div>
                    </a>
                    <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                </div>
            </li>
    
            <div class="topbar-divider d-none d-sm-block"></div>
    
            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                    <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Thông tin
                    </a>

                    <a class="dropdown-item" href="{{ route('admin.user.change_password')}}">
                        <i class="fas fa-key text-gray-400 mr-2"></i> Đổi mật khẩu
                    </a>

                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>{{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
    
        </ul>
    
    </nav>
    <!-- End of Topbar -->