routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::group(['middleware' => 'localization', 'prefix' => Session::get('app.locale')], function() {

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'prefix' => 'qlch',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/', 'HomeController@index')->name('index');

    Route::get('/forgot-password', function () {
        return view('admin.forms.forgot_password');
    })->name('forgot-password');

    Route::get('/user/index','UserController@index')->name('user.index');
    Route::get('/user/create','UserController@create')->name('user.create');
    Route::get('/user/change-password','UserController@changePassWord')->name('user.change_password');
    Route::post('/user/save-change-password','UserController@saveChangePassWord')->name('user.save_change_pass');
    Route::post('/user/register','RegisterController@register')->name('user.register');
    Route::get('/user/edit/{id}','UserController@edit')->name('user.edit');
    Route::post('/user/update/{id}','UserController@update')->name('user.update');
    Route::delete('/user/delete/{id}','UserController@delete')->name('user.delete');

    Route::get('/permission','PermissionController@index')->name('permission.index');
    Route::post('/permission/update','PermissionController@update')->name('permission.update');

    Route::get('/roles','RoleController@index')->name('role.index');
    Route::get('/roles/create','RoleController@create')->name('role.create');
    Route::get('/roles/create/user','RoleController@createUser')->name('role.create_user');
    Route::post('/roles/store/user','RoleController@storeUser')->name('role.store.user');
    Route::post('/roles/save','RoleController@save')->name('role.save');
    Route::post('/roles/update','RoleController@update')->name('role.update');
    Route::delete('/roles/delete/{id}','RoleController@delete')->name('role.delete');

    Route::get('/invoice/index','InvoiceController@index')->name('invoice.index');
    Route::get('/invoice/list','InvoiceController@list')->name('invoice.list');
    Route::get('/invoice/customer-pay','InvoiceController@customerPay')->name('invoice.customer_pay');
    Route::post('/invoice/customer-pay-post','InvoiceController@customerPayPost')->name('invoice.customer_pay_post');
    Route::post('/invoice/change-status','InvoiceController@chaneStatusInvoice')->name('invoice.status');
    Route::get('/invoice/censorship','InvoiceController@getInvoiceCensorship')->name('invoice.censorship');
    Route::post('/invoice/is-censorship','InvoiceController@isCensorship')->name('invoice.is-censorship');
    Route::delete('/invoice/delete/{id}','InvoiceController@delete')->name('invoice.delete');
    Route::get('/invoice/report','InvoiceController@reportInvoice')->name('invoice.report');
    Route::get('/invoice/report/debt','InvoiceController@reportInvoiceDebt')->name('invoice.report.debt');
    Route::get('/invoice/search/name-production','InvoiceController@searchNameProduction')->name('invoice.search.name_production');

    Route::get('/customers','CustomerController@index')->name('customer.index');
    Route::get('/customers/create','CustomerController@create')->name('customer.create');
    Route::get('/customer-edit/{id}','CustomerController@edit')->name('customer.edit');
    Route::get('/customer-debt','CustomerController@getCustomerDebt')->name('customer.debt');
    Route::get('/customer/search/customer-invoice','CustomerController@getCustomerInvoice')->name('search.customer_invoice');
    Route::get('/customer/report/retail','CustomerController@reportRetail')->name('customer.report.retail');
    Route::get('/customer/report/wholesale','CustomerController@reportWholesale')->name('customer.report.wholesale');
    Route::get('/customer/{id}/list-invoice','CustomerController@getlistInvoice')->name('custome_list_invoice');
    Route::post('/customer/invoice-infor','CustomerController@getCustomerInvoiceInfor')->name('custome_invoice_infor');
    Route::post('/customer/store','CustomerController@store')->name('customer.store');
    Route::post('/customer/update/{id}','CustomerController@update')->name('customer.update');
    Route::delete('/customer/delete/{id}','CustomerController@delete')->name('customer.delete');
    Route::get('/customer/history-pays/{id}','CustomerController@historyPays')->name('customer.history_pays');
});

// ==== inoice ====
Route::group([
    'namespace' => 'Admin',
    'middleware' => ['auth']
], function() {
    Route::get('/create-order','InvoiceController@create')->name('create-order');
    Route::post('/invoice/save','InvoiceController@save')->name('invoice/save');
    Route::get('/invoice/print/{id}','InvoiceController@printInvoice')->name('invoice/print');
    Route::get('/invoice/print_back/{id}','InvoiceController@printInvoiceBack')->name('invoice/printBack');
    Route::get('/invoice/printA4/{id}','InvoiceController@printInvoiceA4')->name('invoice/printA4');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    const NOT_ACTIVE = 1;
    const ACTIVE = 2;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'full_name', 'password', 'phone', 'email', 'address', 'birthday', 'deleted_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    /**
     * get all user 
     * @return [collect]
     */
    public function getAll()
    {
        return self::withTrashed()->select('id', 'full_name', 'name', 'phone', 'email', 'address', 'birthday', 'status', 'created_at', 'deleted_at')
            ->with('roles')
            ->orderBy('created_at', 'DESC')
            ->get();
    }
    
    /**
     * get roles of user
     * @return type
     */
    public function getRolesUser()
    {
        $arrRole = [];
        if ($this->roles) {
            foreach ($this->roles as $role) {
                $arrRole[] = [
                    'id' => $role->id,
                    'name' => $role->name,
                ];
            }
        }
        return $arrRole;
    }
    
    /**
     *  mẫu code lây roles va user
     * @return type
     */
    public function report_roles()
    {
        $roles = Role::all();
        $users = User::with('roles')->get();
        $nonmembers = $users->reject(function ($user, $key) {
            return $user->hasRole('Member');
        });
        return view('admin.report_roles', ['roles'=>$roles, 'nonmembers' => $nonmembers]);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Exception;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * get list employee.
     *
     * @return
     */
    public function index()
    {
        if(!Auth::user()->hasPermissionTo('create user')) {
            return view('admin.error_permission');
        }
        $user = new User;
        $param = [
            'users' => $user->getAll(),
        ];
        return view('admin.users.index', $param);
    }
    
    /**
     * get list employee.
     *
     * @return
     */
    public function create()
    {
        if(!Auth::user()->hasPermissionTo('create user')) {
            return view('admin.error_permission');
        }
        return view('admin.users.create');
    }

    /**
     * edit employee
     * @param  [int] $id
     * @return [type]
     */
    public function edit($id)
    {
        if(!Auth::user()->hasPermissionTo('create user')) {
            return view('admin.error_permission');
        }
        $user = User::withTrashed()->find($id);
        if (!$user) {
            return redirect()->back()->withErrors('Không tìm thấy nhân viên');
        }
        $param = [
            'user' => $user,
        ];
        return view('admin.users.edit', $param);
    }

    /**
     * update employee
     * @param  [int] $id
     * @return [type]
     */
    public function update($id, Request $request)
    {
        if(!Auth::user()->hasPermissionTo('create user')) {
            return view('admin.error_permission');
        }
        $user = User::withTrashed()->find($id);
        if (!$user) {
            return redirect()->back()->withErrors('Có lỗi sảy ra');
        }
        $validator = Validator::make($request->all(), [
                'full_name' => ['required', 'string', 'max:255'],
                'name' => ['required', 'string', 'max:255', 'unique:users,name,' . $id],
            ]
        );
        if ($request->status == User::ACTIVE) {
            $deletedAt = null;
        } else {
            $deletedAt = Carbon::now();
        }
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }
        $data = $request->all();
        try {
            $user->update([
                'name' => $data['name'],
                'full_name' => $data['full_name'],
                'phone' => $data['phone'],
                'email' => $data['email'],
                'address' => $data['address'],
                'birthday' => $data['birthday'],
                'deleted_at' => $deletedAt,
            ]);
            return redirect()->back()->with('message', 'Cập nhật thành công!');
        } catch (Exception $e) {
            Log::error($e);
            return redirect()->back()->withErrors('Có lỗi sảy ra');
        }
    }

    /**
     * delete 
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function delete($id)
    {
        if(!Auth::user()->hasPermissionTo('create user')) {
            return view('admin.error_permission');
        }
        $user = User::find($id);
        if ($user->hasRole('sup admin')) {
            return redirect()->back()->withErrors('Nhân viên này không thể xóa');
        }
        if (!$user) {
            return redirect()->back()->withErrors('Có lỗi sảy ra');
        }
        try {
            $user->delete();
            return redirect()->back()->with('message', 'Xóa thành công!');
        } catch (Exception $e) {
            return redirect()->back()->withErrors('Có lỗi sảy ra');
        }
    }

    public function changePassWord()
    {
       return view('admin.users.change_passowrd');
    }

    public function saveChangePassWord(Request $request)
    {
        $messages = [
            'passwordOld.required' => 'Không để trống mật khẩu cũ',
            'passwordNew.required' => 'Không để trống mật khẩu mới',
            'passwordAgain.required' => 'Không để trống mật khẩu nhập lại',
            'passwordNew.min' => 'Mật khẩu phải lớn hơn 8 ký tự',
            'passwordAgain.same' => 'Mật khẩu nhập lại không giống mật khẩu mới',
        ];

        $this->validate($request, [
            'passwordOld' => 'required',
            'passwordNew' => 'required|min:8|string',
            'passwordAgain' => 'required|same:passwordNew',
        ], $messages);


        $data = $request->all();

        $user = Auth::user();
        if(!\Hash::check($data['passwordOld'], $user->password)) {
            return redirect()->back()->withErrors('Mật khẩu hiện tại không đúng!');
        }else{
            $user->password = bcrypt($request->get('passwordNew'));
            $user->save();
        }
        return redirect()->back()->with("message","Thay đổi mật khẩu thành công!");
    }
}

resources/views/admin/users/change_passowrd.blade.php
@extends('admin.layouts.default')

@section('css')

@endsection
<?php
    use App\User;
?>
@section('content')
<div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Thay đổi mật khẩu</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.user.save_change_pass') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="passwordOld" class="col-md-4 col-form-label text-md-right">Mật khẩu hiện tại:<sup class="red">*</sup> </label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" required name="passwordOld">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="passwordNew" class="col-md-4 col-form-label text-md-right">Mật khẩu mới:<sup class="red">*</sup> </label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" required name="passwordNew">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="passwordNew" class="col-md-4 col-form-label text-md-right">Nhập lại mật khẩu mới:<sup class="red">*</sup> </label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" required name="passwordAgain">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Lưu thay đổi') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
   <div class="container">
       
   </div>
@endsection

resources/views/admin/users/create.blade.php
@extends('admin.layouts.default')

@section('css')

@endsection
<?php
    use App\User;
?>
@section('content')
<div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Thêm nhân viên</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.user.register') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="full_name" class="col-md-4 col-form-label text-md-right">Họ và tên:<sup class="red">*</sup> </label>

                            <div class="col-md-6">
                                <input id="full_name" type="text" class="form-control @error('full_name') is-invalid @enderror" name="full_name" value="{{ old('full_name') }}" required autocomplete="full_name" autofocus>

                                @error('full_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Tên đăng nhập:<sup class="red">*</sup> </label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password:') }}<sup class="red">*</sup></label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Nhập lại Password:') }}<sup class="red">*</sup></label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">Số ĐT:</label>

                            <div class="col-md-6">
                                <input id="phone" type="number" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('name') }}" autocomplete="phone" autofocus>

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">Địa chỉ:</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror" name="address" value="{{ old('address') }}" autocomplete="address" autofocus>

                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="birthday" class="col-md-4 col-form-label text-md-right">Ngày sinh:</label>

                            <div class="col-md-6">
                                <input id="birthday" type="date" class="form-control @error('birthday') is-invalid @enderror" name="birthday" value="{{ old('birthday') }}" autocomplete="birthday" autofocus>

                                @error('birthday')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Lưu') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
   <div class="container">
       
   </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.default')

@section('css')
    <style>
        .badge {
            padding: 5px .6em;
        }
    </style>
@endsection
<?php
    use App\User;
?>

@section('content')
<a href="{{ route('admin.user.create') }}" class="btn btn-success mb-4" role="button" target="_bank">
    <i class="fas fa-plus"></i> Thêm mới nhân viên
</a>
<div class="table-responsive">
    <table class="table table-hover table-striped view-user">
        <thead class="bg-success">
            <tr class="">
                <th scope="col">STT</th>
                <th scope="col">Tên nhân viên</th>
                <th scope="col">Tên đăng nhập</th>
                <th scope="col">Số điện thoại</th>
                <th scope="col">Chức vụ</th>
                <th scope="col">Trạng thái</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @php $i = 0; @endphp
            @foreach($users as $key => $user)
            <tr>
                <th scope="row">{{ ++$i }}</th>
                <td>{{ $user->full_name }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->phone }}</td>
                <td>
                    @php
                        $userRoles = $user->getRolesUser();
                        if (count($userRoles)) {
                            foreach ($userRoles as $role) {
                                echo ' <span class="badge badge-secondary"> ' . $role['name'] . '</span> ';
                            }
                        }
                    @endphp
                </td>
                <td>
                    @if (empty($user->deleted_at))
                    <span class="badge badge-success">Hoạt động</span>
                    @else
                    <span class="badge badge-danger">Đóng</span>
                    @endif
                </td>
                <td class="view-pen-trash">
                    <button type="button" class="btn btn-info modal-view" title="Xem chi tiết" data-toggle="modal" data-target="#myModal" data-row="{{ $users[$key] }}"><i class="fas fa-eye"></i>
                    </button>
                    <a href="{{ route('admin.user.edit', ['id' => $user->id]) }}" class="btn btn-primary"data-toggle="tooltip" title="sửa thông tin" data-placement="left" role="button" target="_bank"><i class="fas fa-pen"></i>
                    </a>
                    @if (!$user->hasRole('sup admin'))
                    <a class="btn btn-danger delete-message-name" data-toggle="tooltip" title="Xóa nhân viên" data-placement="right"
                        data-name="{{ $user->name }}" style="color: #ffff"
                        data-message="Bạn có muốn xóa nhân viên: "><i class="far fa-trash-alt"></i>
                        <form class="delete" action="{{ route('admin.user.delete', ['id' => $user->id]) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field() }}
                        </form>
                    </a>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="text-center">
        {{-- {{ $users->links() }} --}}
    </div>
</div>
<!-- The Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title text-center">Thông tin nhân viên</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-6 modal-col1">
                    </div>
                    <div class="col-sm-6 modal-col2">
                    </div>
                </div>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
    <script src="{{ asset('js/user/index.js') }}"></script>
@endsection